"""gender_delete_cascade

Revision ID: 21fd2a2d8950
Revises: 6a9e7e0acdcb
Create Date: 2022-09-26 19:29:41.182816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21fd2a2d8950'
down_revision = '6a9e7e0acdcb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('gender', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'gender')
    # ### end Alembic commands ###
