"""weight_in_food

Revision ID: 6a9e7e0acdcb
Revises: 6f1b80fff148
Create Date: 2022-09-26 13:50:45.969503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a9e7e0acdcb'
down_revision = '6f1b80fff148'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('foods', sa.Column('food_weight', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('foods', 'food_weight')
    # ### end Alembic commands ###
